version: "3.3"
services:
  app:
    image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
    ports:
      - ${DC_APP_PORT}:${DC_APP_PORT}
    networks:
      - micro_service

networks:
  micro_service:
    external:
      name: micro_service






#reescrevendo

# version: "3.3"
# services:
#   app:
#     image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
#     ports:
#       - ${DC_APP_PORT}:${DC_APP_PORT}
#     networks:
#       - micro_service

# networks:
#   micro_service:
#     external:
#       name: micro_service